version: '3'

services:
    bo-ui:
        container_name: seakun-ui
        build:
            context: .
            dockerfile: ./_build/Dockerfile
        volumes:
            - ./_build/nginx/sites-available:/etc/nginx/sites-available:ro
        ports:
            - 80:80
            - 443:443