export const packageList = [
  {
    id: 1,
    restaurantName: 'Voyage Harris Harmoni',
    name: 'All You Can Eat - Lunch',
    package: 'Paket Individu',
    type: 'lunch',
    memberType: 'single',
    logo: '/images/all you can eat/menu/logo.png',
    image: '/images/all you can eat/menu/menu-0.jpg',
    isAvailable: true,
    detailPrice: {
      originalPrice: 338000,
      vendorPrice: 358000,
      discountPrice: 202800,
      adminPrice: 20200,
      finalPrice: 223000,
    },
    voucher: {
      expired: '12 Desember 2021',
    },
    terms: [
      'lorem ipsum',
      'lorem imsum',
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem doloribus dolore, obcaecati hic voluptatem praesentium adipisci provident voluptates odit quos.',
      'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fugiat, architecto molestiae nisi ea repudiandae officiis nihil placeat, esse, beatae repellendus quibusdam quae assumenda itaque illo magnam doloremque dolorum aspernatur voluptates.',
      'lorem ipsum',
    ],
    isShowTerms: false,
  },
  {
    id: 2,
    restaurantName: 'Voyage Harris Harmoni',
    name: 'All You Can Eat - Lunch',
    package: 'Paket Rombongan',
    type: 'lunch',
    memberType: 'group',
    logo: '/images/all you can eat/menu/logo.png',
    image: '/images/all you can eat/menu/menu-0.jpg',
    isAvailable: true,
    detailPrice: {
      originalPrice: 338000,
      vendorPrice: 358000,
      discountPrice: 202800,
      adminPrice: 15200,
      finalPrice: 218000,
    },
    voucher: {
      expired: '12 Desember 2021',
    },
    terms: [
      'lorem ipsum',
      'lorem imsum',
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem doloribus dolore, obcaecati hic voluptatem praesentium adipisci provident voluptates odit quos.',
      'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fugiat, architecto molestiae nisi ea repudiandae officiis nihil placeat, esse, beatae repellendus quibusdam quae assumenda itaque illo magnam doloremque dolorum aspernatur voluptates.',
      'lorem ipsum',
    ],
    isShowTerms: false,
  },
  {
    id: 3,
    restaurantName: 'Voyage Harris Harmoni',
    name: 'All You Can Eat - Dinner',
    package: 'Paket Individu',
    type: 'dinner',
    memberType: 'single',
    logo: '/images/all you can eat/menu/logo.png',
    image: '/images/all you can eat/menu/menu-0.jpg',
    isAvailable: true,
    detailPrice: {
      originalPrice: 338000,
      vendorPrice: 358000,
      discountPrice: 214800,
      adminPrice: 20200,
      finalPrice: 235000,
    },
    voucher: {
      expired: '12 Desember 2021',
    },
    terms: [
      'lorem ipsum',
      'lorem imsum',
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem doloribus dolore, obcaecati hic voluptatem praesentium adipisci provident voluptates odit quos.',
      'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fugiat, architecto molestiae nisi ea repudiandae officiis nihil placeat, esse, beatae repellendus quibusdam quae assumenda itaque illo magnam doloremque dolorum aspernatur voluptates.',
      'lorem ipsum',
    ],
    isShowTerms: false,
  },
  {
    id: 4,
    restaurantName: 'Voyage Harris Harmoni',
    name: 'All You Can Eat - Dinner',
    package: 'Paket Rombongan',
    type: 'dinner',
    memberType: 'group',
    logo: '/images/all you can eat/menu/logo.png',
    image: '/images/all you can eat/menu/menu-0.jpg',
    isAvailable: true,
    detailPrice: {
      originalPrice: 338000,
      vendorPrice: 358000,
      discountPrice: 214800,
      adminPrice: 15200,
      finalPrice: 230000,
    },
    voucher: {
      expired: '12 Desember 2021',
    },
    terms: [
      'lorem ipsum',
      'lorem imsum',
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem doloribus dolore, obcaecati hic voluptatem praesentium adipisci provident voluptates odit quos.',
      'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fugiat, architecto molestiae nisi ea repudiandae officiis nihil placeat, esse, beatae repellendus quibusdam quae assumenda itaque illo magnam doloremque dolorum aspernatur voluptates.',
      'lorem ipsum',
    ],
    isShowTerms: false,
  },
];
