export const packageList = [
  {
    id: 1,
    restaurantName: 'Voyage Harris Harmoni',
    name: 'All You Can Eat - Lunch',
    package: 'Paket Cari Teman',
    type: 'lunch',
    image: '/images/all you can eat/menu/Voyage-03.jpg',
    memberType: 'single',
    logo: '/images/all you can eat/menu/logo.png',
    isAvailable: true,
    isPreOrder: true,
    minimumPeople: 1,
    detailPrice: {
      originalPrice: 338000,
      vendorPrice: 358000,
      discountPrice: 202800,
      adminPrice: 20200,
      finalPrice: 223000,
    },
    voucher: {
      expired: '12 Desember 2021',
    },
    terms: [
      'Biaya yang dibebankan dalam pembelian user adalah biaya makan All You Can Eat di Restoran Voyage dan biaya admin Seakun.id',
      'Data user akan dimasukkan dalam waiting list setelah user melakukan pendaftaran Paket Cari Teman  di Seakun.id',
      'Jika paket cari teman sudah terpenuhi, maka user diharuskan melunasi pembayaran di Seakun.id',
      'User diwajibkan untuk menghubungi Restoran Voyage maksimal H-1 sebelum kedatangan dan user dapat langsung makan  All You Can Eat di Restoran Voyage dengan menunjukkan kode voucher yang dikirimkan via email oleh Seakun.id',
      'Kode voucher akan diberikan kepada setiap user, dan user diperbolehkan untuk datang sendiri atau bersama dengan teman dalam program ini.',
      'Jika user tidak mengkonfirmasi kehadirannya kepada Restoran Voyage, maka Restoran Voyage dan Seakun.id tidak bertanggung jawab apabila kode voucher ridak dapat digunakan atau All You Can Eat tidak dapat dipersiapkan.',
      'User harus datang di periode dan waktu yang telah ditentukan, jika user tidak datang dalam waktu periode yang ditentukan, maka uang tidak dapat dikembalikan kepada user.',
      'Jika user dalam suatu grup tidak terpenuhi sampai pada periode dan waktu yang telah ditentukan, maka tersedia 2 pilihan sebagai berikut: a) User menunggu sampai pada periode dan waktu patungan di Restoran Voyage selanjutnya dan uang user akan ditahan oleh Seakun.id untuk dibayarkan pada periode selanjutnya. b) Uang akan dikembalikan 100% ke user ',
      'Jika user membutuhkan bantuan atau pertanyaan terkait program patungan All You Can Eat di Restoran Voyage, maka dapat langsung menghubungi nomor admin Seakun.id.',
    ],
    isShowTerms: false,
    isShowPrice: false,
  },
  {
    id: 2,
    restaurantName: 'Voyage Harris Harmoni',
    name: 'All You Can Eat - Lunch',
    package: 'Paket Rombongan',
    type: 'lunch',
    image: '/images/all you can eat/menu/Voyage-03.jpg',
    memberType: 'group',
    logo: '/images/all you can eat/menu/logo.png',
    isAvailable: true,
    isPreOrder: false,
    minimumPeople: 2,
    detailPrice: {
      originalPrice: 338000,
      vendorPrice: 358000,
      discountPrice: 202800,
      adminPrice: 15200,
      finalPrice: 218000,
    },
    voucher: {
      expired: '12 Desember 2021',
    },
    terms: [
      'Biaya yang dibebankan dalam pembelian user adalah biaya makan All You Can Eat di Restoran Voyage dan biaya admin Seakun.id',
      'User diwajibkan untuk menghubungi Restoran Voyage maksimal H-1 sebelum kedatangan dan user dapat langsung makan  All You Can Eat di Restoran Voyage dengan menunjukkan kode voucher yang dikirimkan via email oleh Seakun.id',
      'Kode voucher akan diberikan kepada setiap user, dan user diperbolehkan untuk datang sendiri atau bersama dengan teman dalam program ini.',
      'Jika user tidak mengkonfirmasi kehadirannya kepada Restoran Voyage, maka Restoran Voyage dan Seakun.id tidak bertanggung jawab apabila kode voucher ridak dapat digunakan atau All You Can Eat tidak dapat dipersiapkan.',
      'User harus datang di periode dan waktu yang telah ditentukan, jika user tidak datang dalam waktu periode yang ditentukan, maka uang tidak dapat dikembalikan kepada user.',
      'Jika user membutuhkan bantuan atau pertanyaan terkait program patungan All You Can Eat di Restoran Voyage, maka dapat langsung menghubungi nomor admin Seakun.id.',
    ],
    isShowTerms: false,
    isShowPrice: false,
  },
  {
    id: 3,
    restaurantName: 'Voyage Harris Harmoni',
    name: 'All You Can Eat - Dinner',
    package: 'Paket Cari Teman',
    type: 'dinner',
    image: 'images/all you can eat/menu/Voyage-02.jpg',
    memberType: 'single',
    logo: '/images/all you can eat/menu/logo.png',
    isAvailable: true,
    isPreOrder: true,
    minimumPeople: 1,
    detailPrice: {
      originalPrice: 338000,
      vendorPrice: 358000,
      discountPrice: 214800,
      adminPrice: 20200,
      finalPrice: 235000,
    },
    voucher: {
      expired: '12 Desember 2021',
    },
    terms: [
      'Biaya yang dibebankan dalam pembelian user adalah biaya makan All You Can Eat di Restoran Voyage dan biaya admin Seakun.id',
      'Data user akan dimasukkan dalam waiting list setelah user melakukan pendaftaran Paket Cari Teman  di Seakun.id',
      'Jika paket cari teman sudah terpenuhi, maka user diharuskan melunasi pembayaran di Seakun.id',
      'User diwajibkan untuk menghubungi Restoran Voyage maksimal H-1 sebelum kedatangan dan user dapat langsung makan  All You Can Eat di Restoran Voyage dengan menunjukkan kode voucher yang dikirimkan via email oleh Seakun.id',
      'Kode voucher akan diberikan kepada setiap user, dan user diperbolehkan untuk datang sendiri atau bersama dengan teman dalam program ini.',
      'Jika user tidak mengkonfirmasi kehadirannya kepada Restoran Voyage, maka Restoran Voyage dan Seakun.id tidak bertanggung jawab apabila kode voucher ridak dapat digunakan atau All You Can Eat tidak dapat dipersiapkan.',
      'User harus datang di periode dan waktu yang telah ditentukan, jika user tidak datang dalam waktu periode yang ditentukan, maka uang tidak dapat dikembalikan kepada user.',
      'Jika user dalam suatu grup tidak terpenuhi sampai pada periode dan waktu yang telah ditentukan, maka tersedia 2 pilihan sebagai berikut: a) User menunggu sampai pada periode dan waktu patungan di Restoran Voyage selanjutnya dan uang user akan ditahan oleh Seakun.id untuk dibayarkan pada periode selanjutnya. b) Uang akan dikembalikan 100% ke user ',
      'Jika user membutuhkan bantuan atau pertanyaan terkait program patungan All You Can Eat di Restoran Voyage, maka dapat langsung menghubungi nomor admin Seakun.id.',
    ],
    isShowTerms: false,
    isShowPrice: false,
  },
  {
    id: 4,
    restaurantName: 'Voyage Harris Harmoni',
    name: 'All You Can Eat - Dinner',
    package: 'Paket Rombongan',
    type: 'dinner',
    image: 'images/all you can eat/menu/Voyage-02.jpg',
    memberType: 'group',
    logo: '/images/all you can eat/menu/logo.png',
    isAvailable: true,
    isPreOrder: false,
    minimumPeople: 2,
    detailPrice: {
      originalPrice: 338000,
      vendorPrice: 358000,
      discountPrice: 214800,
      adminPrice: 15200,
      finalPrice: 230000,
    },
    voucher: {
      expired: '12 Desember 2021',
    },
    terms: [
      'Biaya yang dibebankan dalam pembelian user adalah biaya makan All You Can Eat di Restoran Voyage dan biaya admin Seakun.id',
      'User diwajibkan untuk menghubungi Restoran Voyage maksimal H-1 sebelum kedatangan dan user dapat langsung makan  All You Can Eat di Restoran Voyage dengan menunjukkan kode voucher yang dikirimkan via email oleh Seakun.id',
      'Kode voucher akan diberikan kepada setiap user, dan user diperbolehkan untuk datang sendiri atau bersama dengan teman dalam program ini.',
      'Jika user tidak mengkonfirmasi kehadirannya kepada Restoran Voyage, maka Restoran Voyage dan Seakun.id tidak bertanggung jawab apabila kode voucher ridak dapat digunakan atau All You Can Eat tidak dapat dipersiapkan.',
      'User harus datang di periode dan waktu yang telah ditentukan, jika user tidak datang dalam waktu periode yang ditentukan, maka uang tidak dapat dikembalikan kepada user.',
      'Jika user membutuhkan bantuan atau pertanyaan terkait program patungan All You Can Eat di Restoran Voyage, maka dapat langsung menghubungi nomor admin Seakun.id.',
    ],
    isShowTerms: false,
    isShowPrice: false,
  },
];
